# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = 'webserver'

  config.vm.network "private_network", ip: "192.168.50.100"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "webserver.yml"
    ansible.become = true
  end

end
