---
  - name: Yum Install Nginx
    yum:
      name: nginx
      state: present
  - name: Startup & Enable Nginx
    systemd:
        state: started
        daemon_reload: yes
        name: nginx
        enabled: True
  - name: Setup Firewall
    systemd:
      state: started
      name: firewalld
      enabled: True
  - firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Reload Firewall
    command: firewall-cmd --reload
  - name: Setup Site
    file: path=/var/www/portfolio state=directory owner=root group=root mode=755
  - copy:
      src: "{{ item }}"
      dest: /var/www/portfolio
      owner: root
      group: root
      mode: 0644
    with_fileglob:
        - ./files/site/*
  - name: SELinux
    command: chcon -Rt httpd_sys_content_t /var/www/
  - copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644
    with_items:
      - { src: './files/ws-configs/nginx.conf', dest: '/etc/nginx/nginx.conf'}
  - name: Restart Nginx
    systemd:
      state: restarted
      name: nginx
