#! /bin/bash
# site setup

yum update -y
yum install -y epel-release
yum install -y nginx


echo "+++> RELOAD & Start NGINX"
systemctl daemon-reload
systemctl enable nginx.service
systemctl start nginx.service

systemctl enable firewalld
systemctl start firewalld
firewall-cmd --zone=public --permanent --add-service=http
# firewall-cmd --zone=public --permanent --add-service=https
firewall-cmd --reload


# mkdir -p /var/www/portfolio
# cp -pvr /tmp/site/* /var/www/portfolio
# chown -R root:root /var/www/portfolio
# chmod 755 /var/www/portfolio

# echo "Update NGINX.conf"
# sed -i '/root/c\         root /var/www/portfolio;' /etc/nginx/nginx.conf

echo "Add Path to SELINUX"
# chcon -Rt httpd_sys_content_t /var/www/

# SSL
echo "Setup SSL"
# mkdir /etc/ssl/private
# chmod 700 /etc/ssl/private
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
# -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
# -subj "/C=US/ST=New York/L=New York/O=Global Security/OU=IT Department/CN=192.168.50.100"
#
# openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

echo 'Configs...'
# cp -pvr /tmp/configs/nginx.conf /etc/nginx/nginx.conf
# cp -pvr /tmp/configs/http.conf /etc/nginx/conf.d/http.conf
# cp -pvr /tmp/configs/https.conf /etc/nginx/conf.d/https.conf

# chmod 644 /etc/nginx/nginx.conf /etc/nginx/conf.d/http.conf
# chown root:root /etc/nginx/nginx.conf /etc/nginx/conf.d/http.conf

echo 'Restarting NGINX...'
systemctl restart nginx

echo "Clean up"
yum clean all
# rm -rf /tmp/configs
# rm -rf /tmp/site

echo ''
echo 'Done!'
